# -*- coding: utf-8 -*-
"""Copy of OOP-II(w8).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17fqgny-990AE0kmEx2wZe5BfxGL5NmMz

OOP-II
"""

class Phone:
  def call(self):
    print("we can call")
  def text(self):
    print("we can text")
class samsung(Phone):
  def photo(self):
    print("we can click photo")

s = samsung()
s.call()
s.text()
s.photo() 

issubclass(Phone, samsung)

class Computer():
  def __init__(self, computer, ram, storage):
    self.computer = computer
    self.ram = ram
    self.storage = storage
class Mobile(Computer):
  def __init__(self, computer, ram, storage, model):
    super().__init__( computer, ram, storage)
    self.model = model

a = Mobile('Apple', 2, 64, 'iphn x')
print(a.computer)
print(a.ram)

"""Method Overriding"""

class Phone:
  def __init__(self):
    print("Hello World")
class samsung(Phone):
  def __init__(self):
    print("Hello")
s = samsung()

class Class1:
  def m(self):
    print("In class1")
class Class2:
  def m(self):
    print("In class2")
class All(Class1, Class2):
  def m(self):
    print("in all class")
    Class1.m(self)
    Class2.m(self)

obj = All()
obj.m()