# -*- coding: utf-8 -*-
"""Lab Session 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V25aVoOhsnU9N95XIZuj7NieX5cg_QDT
"""

#creating list

lst0=[1,2,3,32,2.23,43.23,"python",[2,32,3]]
print(lst0)
lst1=[]
print(lst1)
lst2=list()
print(lst2)

#iterating list

lst0=[1,2,3,32,2.23,43.23,"python",[2,32,3]]
for i in lst0:
    print(i,end=' ')
print('')

#iterating list

lst0=[1,2,3,32,2.23,43.23,"python",[2,32,3]]
print(lst0[2])
print(lst0[6])
print(lst0[-2])
print(lst0[-10])

#List operations

lst0=[1,2,3,32,2.23,43.23,"python",[2,32,3]]

print(len(lst0))                #len( ) gives the length of the list

lst0.append([12,2,12,2])        #append( ) inserts an element to the end of the list
print(lst0)

lst0.insert(2,"pandas")         #insert( ) insertes an element on a given index
print(lst0)

lst0.remove(3)                  #remove( ) removes first occurence of an element
print(lst0)

print(lst0.index("python"))     #index( ) returns index of first occurence of an element

print(lst0.count('pandas'))     #count( ) reuturns the number of occurence of an element

print(lst0.reverse())           #reverse( ) makes a reverse list

lst1=lst0.copy()                #copy( ) makes a copy of list
print(lst1)

lst0.clear()                    #clear( ) makes the list empty
print(lst0)

#lsit slicing

lst0=[1,2,3,32,2.23,43.23,"python",[2,32,3]]

print(lst0[2:7])
print(lst0[2:])
print(lst0[:5])
print(lst0[:])

#list sorting

lst2=[1,2,4,2,4,2,4,2,5,6,7,4]

lst3=sorted(lst2)
print(lst3)
print(lst2)
lst2.sort()
print(lst2)

#creating tuple

tp0=(1,2,3,32,2.23,43.23,"python",[2,32,3])
print(tp0)
tp1=()
print(tp1)
tp2=tuple()
print(tp2)

#iterating tuple

tp0=(1,2,3,32,2.23,43.23,"python",[2,32,3])
for i in tp0:
    print(i,end=' ')
print('')

#iterating tuple

tp0=(1,2,3,32,2.23,43.23,"python",[2,32,3])
print(tp0[2])
print(tp0[6])
print(tp[-2])
print(tp[-10])

#inserting into tuple

tp0=(1,2,3,32,2.23,43.23,"python",[2,32,3])
tp0+=("pandas",232,3,232,3)
print(tp0)

#unpacking sequences

lst=[2,3,423,43]
a,b,c,d=lst
print(a)
print(b)
print(c)
print(d)

#unpacking sequences

tp=(2,3,423,43)
a,b,c,d=tp
print(a)
print(b)
print(c)
print(d)